spring.application.name=desi2026
server.port=8080

# Datasource MySQL/MariaDB
spring.datasource.url=jdbc:mysql://localhost:3306/gofracan?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=desi
spring.datasource.password=desi
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.database=MYSQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
